### ISSUE TITLE
Book is marked as complete after page 10

### ISSUE THREAD

**Issue by hillam** [standardebooks/robert-louis-stevenson_treasure-island_milo-winter#1] opened 2017-01-31 01:58 UTC
When I read this book on my Kobo Aura, after attempting to go from page 10/164 to 11/164, my e-reader marks the book as complete. From the table of contents, attempting to skip to any chapter beyond chapter 1 within Part 1 jumps me to Part 1 Chapter 1. I can, however skip to Part 2, etc. 

I'm not having this issue with other books that I've tried, although I only just got the reader (I think it's the first edition Aura, used on eBay). I don't know much of anything about epub, so even advice as to how I can hack the file to work on my device would be helpful.

**Comment by acabal** [comment] 2017-01-31 20:07
Hmm, strange.  If you open up the source you can see that in this book the chapters are fairly short so we divided the xhtml files into 6 parts instead of so many more chapters.  In the ToC the individual chapters are addressed by their IDs, like `text/part-1.xhtml#chapter-1`.

Can you check if you're using the latest software version on your device?  Also if your device is extremely old and there are no software updates available then we might just have to write it off as unsupportable... there are too many ereaders that never get updated with too many quirks for us to be able to make a 100% universally compatible epub.

Are you using the compatible epub file or the epub3 file?

Another ebook that uses ID addressing in the ToC is [North of Boston](https://standardebooks.org/ebooks/robert-frost/north-of-boston).  You can try using that book's ToC, and if it has the same problem, then that's probably the issue here.  Let me know!

**Comment by hillam** [comment] 2017-02-02 23:44
Thanks for your response @acabal!

> Can you check if you're using the latest software version on your device? 

I'm using the latest 3.19 firmware on my first gen Kobo Aura. 

> Are you using the compatible epub file or the epub3 file?

epub

>Also if your device is extremely old and there are no software updates available then we might just have to write it off as unsupportable...

I kind of figured that as a possibility. I thought I'd check to see if there was a specific known compatibility issue here with a known workaround that I might be able to implement on a forked copy. 

I'll give North of Boston a go and update you! 

---

Edit: North of Boston has the same issue, so I think we've found the cause there.

**Comment by hillam** [comment] 2017-02-02 23:49
Also, regarding my reader marking the book as finished after a page turn very early in the book, it happens with 100% consistency between the paragraphs at [lines 60 and 61](https://github.com/standardebooks/robert-louis-stevenson_treasure-island_milo-winter/blob/master/src/epub/text/part-1.xhtml#L60-L61) in the Part 1 source. Very odd. I'll try once more to re-download the book just for good measure.

**Comment by acabal** [comment] 2017-02-09 22:51
OK thanks.  I may be able to get my hands on a Kobo Aura One soon, which I think has a higher firmware version than yours, but I'll see what we can do at that point.

**Comment by acabal** [comment] 2017-02-20 05:15
OK, I've got access to a Kobo Aura One, and I think I've got things sorted out on a preliminary level.  Here's what's happening.

Kobos appear to support basically two kinds of epubs: plain vanilla epubs, like the ones Standard Ebooks produces, and "kepubs", which is some kind of custom epub variant.

When a Kobo loads a regular epub, it falls back to the super shitty Adobe Digital Editions renderer.  Since ADE is so excruciatingly terrible, that's the cause of the issues you've been seeing, and many more, like missing cover art and crappy styling.

When a Kobo loads a kepub, it uses its advanced Webkit-based renderer, which is actually pretty good, all things considered.  It just so happens that books you buy from the Kobo store are kepubs.

So how do you side load a regular epub and get the nice, non-broken rendering engine?  There are two ways:

1. *The easy but bad way*: Rename the file extension from ".epub" to ".kepub.epub".  Then, copy the file to your Kobo using a file manager.  This will force the Kobo to render using the kepub engine, where everything works just about right, **except for these stupid bugs**:

    1. Highlighting and annotation don't work.
    
    2. When you close, then reopen a book, you're sent to the beginning of the last chapter you were on, not the last page you were on.

2. *The longer but good way*: Fortunately we can get nice kepub rendering without sacrificing highlights and locations.  The answer is to just use Calibre, with a special plugin installed, to transfer to your Kobo:

    1. Install the latest version of [Calibre](https://calibre-ebook.com).

    2. Install the KoboTouchExtended plugin: Preferences -> Plugins -> Get New Plugins -> Search for KoboTouchExtended, then restart Calibre.

    3. Add our compatible .epub file (*not* the pure .epub3 file) to your Calibre library, then use Calibre to transfer the ebook over to your Kobo.  Calibre should automatically convert to kepub, plus do additional magic to alleviate the issues you're experiencing.

So far Calibre appears to work really well with the Kobo Aura One.  Not sure about older models.  Give it a shot and let me know!

**Comment by acabal** [comment] 2017-02-20 18:08
I've written up [instructions on using Calibre to transfer epubs to Kobo devices](https://standardebooks.org/help/how-to-use-our-ebooks#kobo).  So far it seems to work really well for me.

Since Calibre does the magic necessary for Kobo to enable acceptable formatting and features I'm going to close this issue.  Please do open another one if problems persist! :)

**Closed as completed by acabal** 2017-02-20 18:08 UTC

**Comment by hillam** [comment] 2017-02-20 22:54
Wow! Well done and thank you for the thorough investigation. Looks like problem solved!
